cogs/general.py
cogs/inspection.py
cogs/moderation.py
core/__init__.py

Added `/audit`, modified type hints and more.

---

cogs/music.py

Current UI:
After pressing skip:
Issue: #48 
Let me know your thoughts on this.

Added skip and volume buttons to the `/now` slash command.

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml

⚠ No Pull request templates were loaded
This Pull request is for **hacktoberfest** and closes #65 
- i have asked to add Issue templates in the repository
- There must be of 4 type bugs, docs, features, others !
- GitHub workflow based issue templates are added.
- They are of 4 default types.
- Blank issue options are `false`
- Make changes in the `.yml` files to customize the issue templates

feat : New issue templates 🛠

---

cogs/music.py

This PR fixes a bug with the `/now` command which:
- Made the view re-appear after timeout, even if the **Skip** button had already been pressed and the embed was gone.

Fixed view appearing after timeout.

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature_request.yml
cogs/music.py

This PR adds a message command which can be used to search, enqueue and play from the content of a message. The name for the command is "Search & Play" for now. The PR also addresses slight improvements to the issue templates.

Add a message command equivalent to `/play`.

---

cogs/inspection.py
cogs/music.py

Fixed broken "Search & Play", a colorful shuffle & more!

---

cogs/music.py

- The instance of `QueueCommandSelect` does not update when the **Shuffle** button is pressed. This might be caused by predefining the select outside and then adding it to the view upon initialization.

Squished some bugs in the Music cog, patched `/volume` and more.

---

.github/ISSUE_TEMPLATE/feature_request.yml
cogs/general.py
cogs/inspection.py
cogs/music.py
core/__init__.py
core/embeds.py
core/global_.py

... and some more teeny-tiny changes.

Modifications to the newly added `/ping` command and more.

---

cogs/music.py

Added `/playrich` and patched Spotify handler.

---

Dockerfile
cogs/general.py
cogs/music.py
docker-compose.yml

Improved `/playrich` command family and implemented Docker Compose.

---

cogs/music.py

Fixed refreshing of selection field in the `/queue` slash command.

---

.github/workflows/linting.yml
Dockerfile
docker-compose.yml

A good thing to note here is this deployment might break some of the upcoming deployments while running on the cloud, but if it doesn't then we're all good :D

Improved CI/CD and Docker Compose workflows for fly.io deployment.

---

cogs/inspection.py

Added new `/revokeinvites` slash command.

---

.github/workflows/formatting.yml
.github/workflows/linting.yml
cogs/moderation.py
core/__init__.py

Added choices to `/slowmode` and separated workflows.

---

cogs/general.py
cogs/inspection.py
cogs/music.py

refact: use or operator instead of ternay

---

cogs/exceptionhandler.py
cogs/moderation.py

This micro-PR fixes a tiny yet urgent bug which hardcoded the number "10" as the purged amount within the notification message for ripple purge command group. It also fixes some message lines in the exception handler.

bugfix: `/ripplepurge` backend message and error handler

---

cogs/inspection.py

bugfix: role lock `/revokeinvites`

---

cogs/moderation.py
core/__init__.py

- Previous webhooks are used for sniping user messages if the authors match in order.

chore: Properly reused webhooks inside `/snipe` command

---

.github/workflows/deploy.yml
.github/workflows/formatting.yml
.github/workflows/linting.yml

[chore] Added concurrency to the GitHub Actions workflows.

---

cogs/moderation.py

(tuning) Snipes are now ordered

---

cogs/moderation.py
cogs/music.py
core/chain.py

[tuning] Better overall `/snipe` command operation and more

---

cogs/general.py

One thing to note, I didn't use `TypicalEmbed` for the embed for this one, because it simply didn't work out since `TypicalEmbed` requires an `Interaction` as an argument. 
[Inspiration!](https://git.poto.cafe/yagich/potomark-bot-rb/)

✨ [feat] Added new listener for emoji reactions, bookmarking feature

---

cogs/general.py
core/embeds.py

- `TypicalEmbed`
- `SmallView`

🔨 [tuning] Better embeds and views, bookmark improvements

---

cogs/general.py

🐛 [bug-fixed] Fix author name on bookmark embed

---

cogs/moderation.py
cogs/music.py
core/__init__.py

🔨 [tuning] Improved moderation commands and fixed more minor bugs

---

.github/workflows/build-image.yml
core/__init__.py

This PR adds a new GitHub Action workflow for automatically building Docker images for IgKnite and adding them to its [GitHub Package registry](https://github.com/features/packages). No code changes have been made.

⚡ [chore] Added support for GitHub Packages registry

---

.github/workflows/formatting.yml
.github/workflows/linting.yml
README.md
cogs/general.py
cogs/inspection.py
cogs/moderation.py
cogs/music.py
core/__init__.py

🔨 [tuning] Improved voice cleanups, restrictions and more

---

cogs/music.py

This PR removes the warning messages which were previously sent by IgKnite when a user left a voice session running inside a voice channel without anybody listening to it.

🔨 [tuning] Voice alerts have been removed

---

cogs/music.py

This PR adds a new role-locked (`BotMod` and `BotAdmin`) slash command named `/togglelock`.
It can be used to lock the current voice state so that users who don't have the following roles won't be able to manipulate the voice state with these commands:
- `/play`
- `/skip`
- `/stop`
- `/volume`
- `/pause`
- `/resume`
- `/leave`
- `/loop`

✨ [feat] Added a new `/togglelock` slash command

---

cogs/inspection.py

This PR modifies the `/userinfo` to display the global name and the username of a user in the title field.

🔨 [tuning] Synchronized `/userinfo` with latest API changes

---

cogs/customization.py
cogs/exceptionhandler.py
cogs/general.py
cogs/inspection.py
cogs/moderation.py
cogs/music.py
core/__init__.py
core/ui.py

✨ [feat] Added `/unassignrole`; tiny, invisible changes & more

---

core/__init__.py
main.py
reboot.py

This PR adds a new `reboot.py` Python script that can be used to restart the bot automatically in the event of a possible HTTP exception / rate-limit indication.

✨ [feat] Added automatic reboots for HTTP exceptions

---

cogs/general.py
requirements.txt

🐛 [bugfix] Bookmarking doesn't rely on internal cache anymore

---

.devcontainer/devcontainer.json
README.md
cogs/music.py
core/__init__.py
pyproject.toml

✨ [feat] Improved voice safety features for paused playback

---

.github/workflows/docker-image.yml
.github/workflows/fly-deploy.yml
fly.toml

🔨 [tuning] Add new deployment workflows
