IgKniteDev/IgKnite

- cogs/general.py
- main.py
> Added `guildinfo` command

- cogs/inspection.py
- core/dataclasses.py
- core/embeds.py
- core/global_.py
> Role locks, random footers & more!

- cogs/general.py
- cogs/inspection.py
- core/bot.py
- core/dataclasses.py
- core/global_.py
- main.py
> Moved variables, renamed `ModRoles` and more.

- README.md
More changes will be made to this markdown file before the initial launch.
> Standardized README.md

- cogs/inspection.py
- core/global_.py
- Added `roleinfo` command.
- Fixed a `SyntaxError` in `core/global_.py` related to type annotations.
> Added `roleinfo` command and fixed a `SyntaxError`

- cogs/moderation.py
> `Moderation` cog & new commands

- cogs/moderation.py
> Set `required` to `True` for some options!

- cogs/moderation.py
All replies made by these commands are ephemeral.
> Implemented all **purge** related commands

- cogs/general.py
- cogs/inspection.py
- cogs/moderation.py
More of an indentation upgrade than a pure commit.
> Add # before command decorators.

- README.md
- cogs/moderation.py
- core/bot.py
- core/global_.py
> Added `/softban`, `/timeout`, `/snipe` and more!

- README.md
- cogs/general.py
- cogs/inspection.py
- core/global_.py
> Fixed critical bug regarding global variable declarations.

- Dockerfile
- README.md
- core/bot.py
- core/global_.py
- main.py
- requirements.txt
> What are you doing? **Docking.**

- cogs/moderation.py
- core/bot.py
- core/decor.py
> Fixed slash command syncing and the `/snipe` command.

- cogs/exceptionhandler.py
- cogs/moderation.py
- core/bot.py
- guicer.py
> Added exception handler, registered commands as long-running and more.

- cogs/customization.py
- cogs/exceptionhandler.py
- main.py
Please note that some of the commands are admin-only!
> `Customization` cog & new commands!

- cogs/customization.py
- cogs/general.py
- cogs/inspection.py
- cogs/moderation.py
- core/bot.py
- core/decor.py
> Restructured method declarations.

- Dockerfile
- cogs/customization.py
- cogs/music.py
- core/__init__.py
- core/bot.py
- core/global_.py
- main.py
- requirements.txt
> Music system foundation and one intentional, little change.

- README.md
One more change is pending till the final push...
> Fine-tuned the root README.md file for the *second* last time before release.

- .dockerignore
- README.md
- fly.toml
> Finalized project :D

- .github/workflows/linting.yml
- README.md
- core/datacls.py
This PR includes small changes to the `.github/workflows/linting.yml` file.
> Updated GitHub Action workflows.

- CONTRIBUTING.md
- README.md
- cogs/moderation.py
This pull request enhances the contribution guidelines (CONTRIBUTING.md) provided with the repository to contain topics such as the command structure. The root ReadMe markdown file (README.md) has also been tweaked a bit.
> Updated contribution guidelines and markdown.

- cogs/inspection.py
Fixes the updated InviteMenu, when there are no invites for the server
> Merge incoming changes

- cogs/music.py
Issue: #48 (only partly, will add volume and skip into another PR)
Let me know your thoughts on the code.
In line 696 raising an error when there is none might not be the most elegant solution, but it is the simplest & cleanest I found.
> Fixed /now command not updating after audio is finished.

- cogs/customization.py
- cogs/inspection.py
- cogs/moderation.py
- cogs/music.py
> Switch to min & max value validation built-into Discord

- README.md
> Embed contributors' images into markdown.

- cogs/general.py
updated, i added 
performance=cpu usage and ram usage
uptime
> Add informative fields to the `/ping` slash command.

- cogs/general.py
> Revert "Add informative fields to the `/ping` slash command."

- cogs/general.py
- core/global_.py
This PR is a short but the reason behind that is I can't think of anything else right now. 
Fix #83
> Added more to `/ping`

- cogs/general.py
> Added a refresh button to the `/ping` slash command.

- .github/pull_request_template.md
- cogs/music.py
> Fine-tuned the tuned `/queue` command, reduced boilerplate and more.

- cogs/moderation.py
> Added: `/senddm`

- cogs/general.py
- core/global_.py
[Example Image](https://cdn.discordapp.com/attachments/1028685303310991512/1030480309092888597/unknown.png)
> Added a new `/help` slash command.

- .flake8
- cogs/exceptionhandler.py
- cogs/general.py
- cogs/music.py
- core/__init__.py
- core/global_.py
> Fixed issues from previous PRs and updated the `/ping` slash command.

- core/embeds.py
**Why?**
To make it easy to create views and add buttons.
> Add TypicalView

- cogs/general.py
- cogs/music.py
- core/embeds.py
- This PR addresses issues from: https://github.com/IgKniteDev/IgKnite/pull/109
> Fixed bugs with `core.embeds.TypicalView` and renamed it.

- .github/workflows/linting.yml
- cogs/customization.py
- cogs/exceptionhandler.py
- cogs/general.py
- cogs/inspection.py
- cogs/moderation.py
- cogs/music.py
- core/__init__.py
- core/bot.py
- core/embeds.py
- core/global_.py
- main.py
> Added Black without string normalization and implemented automations for it.

- cogs/moderation.py
> Add pins related commands

- .github/workflows/linting.yml
- cogs/moderation.py
- core/__init__.py
- main.py
> Fixed formatting errors from newest PR and improved automation.

- cogs/customization.py
> Add color option to /makerole

- cogs/moderation.py
> feat: /slowmode and /noslomo

- cogs/moderation.py
> Add /banword

- .vscode/settings.json
- cogs/customization.py
- cogs/exceptionhandler.py
- cogs/general.py
- cogs/inspection.py
- cogs/moderation.py
- cogs/music.py
- core/__init__.py
- core/embeds.py
- core/global_.py
- main.py
> chore: Improved `/banword`, refactored codebase parts.

- cogs/customization.py
> add /afkvc

- cogs/customization.py
- core/bot.py
> refactor: Updated bot model and the `/afkvc` slash command.

- cogs/moderation.py
> feat: Added `/clearbannedwords`, refactored `/banword` slash command.

- cogs/exceptionhandler.py
> feat: report button in exception handler

- cogs/moderation.py
> feat: added `/showbannedwords`

- cogs/moderation.py
- core/embeds.py
> Using embeds on errors! (in cogs/moderation.py)

- cogs/moderation.py
> feat: Added `/clearnicks` slash command.

- core/__init__.py
This PR doesn't contain any kind of big changes other than version bumps.
> chore: synchronization PR

- cogs/moderation.py
- Messages sent by the same user in order are now resent by the same webhook.
> chore: reused webhooks for similar users

- cogs/moderation.py
This PR fixes a small typo which made the `/snipe` slash command fail.
> bugfix: AttributeError

- cogs/music.py
> Add `/loop` & `/shuffle` commands

- CONTRIBUTING.md
- core/__init__.py
This PR adds [Gitmoji](https://gitmoji.dev/) as a standard for mentioning PRs and commits in short prefix-type emojis.
> 📝 (chore) Updated contribution guidelines

- .github/dependabot.yml
- requirements.txt
> [dependency] Updated requirements.txt

- cogs/inspection.py
- cogs/moderation.py
- cogs/music.py
> :art: [tuning] Formatted codebase and such

- cogs/general.py
- cogs/inspection.py
- cogs/moderation.py
- cogs/music.py
> :zap: [tuning] Improved base for several slash commands

- cogs/music.py
- core/embeds.py
> ✨ [tuning] Added "Clear Queue" button and a new random footer

- cogs/music.py
> :bug: [bug-fixed] Fixed bug with `/resume` command and more

- cogs/music.py
- core/__init__.py
> 🐛 [bug-fixed] Resolved incorrect voice safety

- cogs/music.py
> 🐛 [bug-fixed] Fixed manual disconnect / kick bug and more

- cogs/music.py
- core/__init__.py
This PR modifies the `on_voice_state_update()` event handler inside the music cog to ensure voice safety in an even better way.
> 🔨 [tuning] Better voice safety checks

- cogs/general.py
- cogs/moderation.py
- cogs/music.py
- core/__init__.py
- core/ui.py
> 🔨 [tuning] Improved voice state management and more

- cogs/music.py
- core/__init__.py
This PR improves on the existing **Boosted Mode** feature inside the `/play` slash command and fine-tunes the sound quality. Still needs more work.
> 🔨 [tuning] Improved "Boosted Mode" for the `/play` slash command

- .vscode/extensions.json
- cogs/customization.py
- cogs/general.py
- cogs/inspection.py
- cogs/moderation.py
- cogs/music.py
- core/__init__.py
> ✨ [feat] New, modified command declaration structure

- cogs/inspection.py
- cogs/moderation.py
This PR changes `for` to `async for` as well as other tiny code snippets in some parts of the codebase. No major change has been done.
> 🔨 [tuning] Improved async loops syntax

- cogs/customization.py
- cogs/exceptionhandler.py
- cogs/general.py
- cogs/inspection.py
- cogs/moderation.py
- cogs/music.py
- core/__init__.py
- core/ui.py
This PR modifies how `core.TypicalEmbed` handles titles and descriptions. Instead of using custom functions, the following class now passes positional and keyword-only arguments directly to the `disnake.Embed` class overwrite.
> 🔨 [tuning] Improved code structure for `core.TypicalEmbed`

- cogs/exceptionhandler.py
- core/__init__.py
Fixed a bug which crashed the exception handler cog. This was due to a misalignment with the recent updates to the `core.TypicalEmbed` class.
> 🐛 [bug-fixed] Fixed a bug related to the exception handler

- README.md
- cogs/exceptionhandler.py
- cogs/music.py
- core/__init__.py
> 🔨 [tuning] Structurally updated the exception handler and the music cog

- README.md
- core/__init__.py
- core/bot.py
This PR adds a modified layer of notice board for sunsetting IgKnite once and for all. :(
> 🌆 [tuning] The final pull request.

- cogs/__init__.py
- core/bot.py
- main.py
> feature to manage what extensions to not load
